### ISSUE TITLE
INPUT_PULLUP instead of INPUT

### ISSUE THREAD

**Issue by taHC81** [bercho/dual-function-button#1]
Hello, what about using internal pull-ups?

**Comment by BerranRemzi** [comment]
I added INPUT_PULLUP function, but not tested yet. 
After tests feel free to share your feedback.

**Comment by morrissey007** [comment]
INPUT_PULLUP works perfectly for me. enables me to use a switch that doesn't require an external resistor and so when closed it connects to GND.
Thanks!
