### ISSUE TITLE
Doe this debounce the switch?

### ISSUE THREAD

**Issue by morrissey007** [bercho/dual-function-button#2]
I can't see if this debounces the switch? not sure If I should add debounce delay in my code or reply on this library to do it?

**Comment by BerranRemzi** [comment]
There is no debounce function on code. This can affect short press only.
The best way could be to add debounce code in this library.
If you are implemented this code please share it with community.
If not in the next day I can implement it for you.

**Comment by morrissey007** [comment]
Hi, thank you for the quick reply!  Yes, I understand that it would only affect short press, I don't know how to add this, sorry! It would be great if you could add this?

**Comment by BerranRemzi** [comment]
Done with [https://github.com/BerranRemzi/dual-function-button/commit/9d529a48e09de50c6a1bdab67ddc8c39aa620f3e](url)
By default debounce time is 50ms but you can change it with SetDebounceTimeShort(uint16)

**Comment by morrissey007** [comment]
All tested and fully working! Works superb, not a bounce anywhere.  Thank you so much for such a rapid turn-around.   I will study the code to try and work out how you did it and learn from it. Kind Regards, Clive

**Comment by BerranRemzi** [comment]
I wrote this code long ago and it's not the best code I wrote. If I found some free time I will improve its readability.
